[package]
name = "magriette"
version = "0.1.0"
authors = ["iriri"]
edition = "2018"

repository = "https://github.com/iriri/magriette"
license = "BSD-3-Clause"
description = "This is not a pipe."

[dependencies]
